#!/bin/bash
# Generate src/lib/version.ts from version.json
set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR/.."

VERSION=$(cat "$PROJECT_DIR/version.json" | python3 -c "import sys,json; v=json.load(sys.stdin); print(f'v{v[\"major\"]}.{v[\"minor\"]}.{v[\"patch\"]}')")

cat > "$PROJECT_DIR/src/lib/version.ts" << EOF
// Auto-generated by scripts/generate-version.sh — DO NOT EDIT
export const APP_VERSION = "$VERSION";
EOF

echo "✅ Generated version: $VERSION"
